#!/bin/sh
# omakase-harness hook-stub installer. Generated by init.sh; called by init.sh after
# `lefthook install` and by ensure-present.sh on every checkout (lefthook's npm
# postinstall regenerates the stubs, stripping our blocks — this re-arms them).
# Idempotent (strip-then-insert). Installs two block kinds, both ABOVE lefthook's call:
# fail-closed verify (pre-commit/pre-push) and worktree-bootstrap self-heal (post-checkout).
COMMON="$(cd "$(git rev-parse --git-common-dir 2>/dev/null)" && pwd)" || exit 0
HOOKS_DIR="$COMMON/hooks"

# --- fail-closed verify: block a commit/push when the overlay was wiped. ---
GBEGIN="# >>> omakase-harness fail-closed >>>"
GEND="# <<< omakase-harness fail-closed <<<"
for h in pre-commit pre-push; do
  hf="$HOOKS_DIR/$h"
  [ -f "$hf" ] || continue
  grep -qi 'lefthook' "$hf" 2>/dev/null || continue   # only instrument lefthook-managed stubs — a
  # surviving stock git-lfs hook (e.g. pre-push, when no lefthook job owns it) is left alone on
  # purpose: omakase only fail-closes hooks it actually gates, and pre-commit is always gated.
  awk -v b="$GBEGIN" -v e="$GEND" '$0==b{s=1} !s{print} $0==e{s=0}' "$hf" > "$hf.tmp"
  {
    head -n1 "$hf.tmp"   # the shebang
    printf '%s\n' "$GBEGIN"
    cat <<'GUARD'
# Fail-closed: this runs ABOVE lefthook, so LEFTHOOK=0 does not bypass it;
# the only escape is git's own --no-verify.
omakase_verify="$(git rev-parse --git-common-dir)/omakase/verify-overlay.sh"
if [ -f "$omakase_verify" ]; then
  sh "$omakase_verify" || exit 1
fi
# Gate-runner leg (#72): lefthook's stub below fails OPEN when no branch of
# its call_lefthook chain finds a binary ("Can't find lefthook", exit 0) —
# the wired gates would silently skip. Resolve by omakase's own tiers first;
# a cache-only lefthook is healed by prepending its dir to PATH, so the
# stub's own `lefthook` branch runs the gates. The cache probe is a
# version-agnostic glob on purpose: this block is static text baked into
# installed hooks, and a later lefthook re-pin must not strand them. Unlike
# the overlay verify above, LEFTHOOK=0 IS honored here — with it set the
# stub skips gates by explicit choice, so nothing is SILENTLY skipped.
# Residual: a lefthook reachable only through the stub's exotic branches
# (go tool, bundle exec) is blocked; hooks exist only where init resolved
# lefthook through these same tiers, and LEFTHOOK_BIN is the escape.
if [ "${LEFTHOOK:-}" != "0" ] && [ -z "${LEFTHOOK_BIN:-}" ] \
   && ! command -v lefthook >/dev/null 2>&1 \
   && ! [ -x "$(git rev-parse --show-toplevel 2>/dev/null)/node_modules/.bin/lefthook" ]; then
  omakase_lh_dir=""
  for omakase_lh in "${XDG_CACHE_HOME:-$HOME/.cache}"/omakase/lefthook/*/lefthook; do
    if [ -x "$omakase_lh" ]; then omakase_lh_dir="${omakase_lh%/lefthook}"; break; fi
  done
  if [ -n "$omakase_lh_dir" ]; then
    PATH="$omakase_lh_dir:$PATH"; export PATH
  else
    echo "omakase: BLOCKING — no lefthook found (LEFTHOOK_BIN, PATH, node_modules/.bin, or the omakase cache): the wired gates cannot run." >&2
    echo "omakase: restore it with a bare  omakase init  (self-fetches lefthook), or install lefthook / set LEFTHOOK_BIN. Skip once with LEFTHOOK=0; git --no-verify bypasses hooks entirely." >&2
    exit 1
  fi
fi
GUARD
    printf '%s\n' "$GEND"
    tail -n +2 "$hf.tmp"
  } > "$hf"
  rm -f "$hf.tmp"
  chmod +x "$hf"
done

# --- worktree-bootstrap: self-heal the harness into a fresh `git worktree add`. ---
# A fresh worktree has no (gitignored) lefthook config, so lefthook's post-checkout job
# no-ops and the harness never materializes. This block runs ensure-present.sh straight
# from the SHARED git dir (reachable from every worktree), so a plain `git worktree add`
# — any host: Copilot CLI, bare git, or Claude (alongside its .worktreeinclude copy) —
# bootstraps the harness on creation. Never blocks the checkout (self-heal is best-effort;
# the pre-push fail-closed guard backs it).
WBEGIN="# >>> omakase-harness worktree-bootstrap >>>"
WEND="# <<< omakase-harness worktree-bootstrap <<<"
hf="$HOOKS_DIR/post-checkout"
if [ -f "$hf" ] && grep -qi 'lefthook' "$hf" 2>/dev/null; then
  awk -v b="$WBEGIN" -v e="$WEND" '$0==b{s=1} !s{print} $0==e{s=0}' "$hf" > "$hf.tmp"
  {
    head -n1 "$hf.tmp"   # the shebang
    printf '%s\n' "$WBEGIN"
    cat <<'BOOT'
omakase_ensure="$(git rev-parse --git-common-dir)/omakase/ensure-present.sh"
if [ -f "$omakase_ensure" ]; then
  bash "$omakase_ensure" || true
fi
BOOT
    printf '%s\n' "$WEND"
    tail -n +2 "$hf.tmp"
  } > "$hf"
  rm -f "$hf.tmp"
  chmod +x "$hf"
fi
