#!/usr/bin/env bash
# Behavioral spec for the fail-closed GATE-RUNNER leg install-guards.sh splices
# above lefthook's hook stub (#72). lefthook's own stub fails OPEN when no branch
# of its call_lefthook chain finds a binary ("Can't find lefthook", exit 0) — the
# wired gates silently skip. The spliced block must instead:
#   H1. HEAL: lefthook only in the omakase cache -> exported as LEFTHOOK_BIN so
#       the stub's first branch runs the gates (commit succeeds AND the gate
#       runner demonstrably ran). The cache probe is a version-agnostic glob —
#       proven with a version dir that matches no pin.
#   H6. A DIRECTORY named lefthook in the cache must BLOCK, not heal: [ -x ]
#       alone passes a directory, the stub then finds nothing and falls open —
#       the exact silent skip this block exists to close.
#   H2. BLOCK: no lefthook anywhere -> the commit is REFUSED (exit non-zero,
#       "omakase: BLOCKING" on stderr, no commit created) instead of the silent
#       fail-open skip.
#   H3. LEFTHOOK=0 is honored: same empty machine, LEFTHOOK=0 -> commit succeeds
#       (the stub would skip gates by explicit choice; nothing is SILENTLY lost).
#   H4. LEFTHOOK_BIN override: resolves at tier 1, no block, gates run.
#   H5. Idempotent re-arm: running install-guards.sh twice leaves exactly ONE
#       fail-closed block, and an OLD block between the same markers is REPLACED.
#   H0. The two shipped copies of install-guards.sh (bin/ and the Go binary's
#       embedded template) are byte-identical.
# Hooks are exercised through REAL `git commit` runs under env -i; the hook stub
# is a facsimile of lefthook's generated stub (same shape: LEFTHOOK=0 exit,
# LEFTHOOK_BIN branch, PATH branch, fail-open else) — the real stub is
# regenerated by whatever lefthook version installed it, so the suite pins the
# SHAPE the block must survive, not one lefthook release's byte output.
set -u
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IG="$HERE/../bin/install-guards.sh"
IG_EMBEDDED="$HERE/../internal/templates/files/install-guards.sh"
TMP="${TMPDIR:-/tmp}/omakase-hook-failclosed.$$"
FAILED=0
pass(){ echo "  PASS: $1"; }
fail(){ echo "  FAIL: $1"; FAILED=1; }

# A lefthook-free PATH (idiom of tests/status-parity.test.sh:lhfree_path): built from
# the real PATH + system dirs, skipping any dir that carries a lefthook — a distro
# package at /usr/bin/lefthook must not satisfy the stub's PATH branch and turn the
# block scenarios vacuous, while git/sh stay reachable.
lhfree_path(){
  local out="" d oldifs="$IFS"
  IFS=':'
  for d in $PATH /usr/bin /bin /usr/sbin /sbin; do
    IFS="$oldifs"
    [ -n "$d" ] || { IFS=':'; continue; }
    [ -x "$d/lefthook" ] && { IFS=':'; continue; }
    case ":$out:" in *":$d:"*) IFS=':'; continue;; esac
    out="${out:+$out:}$d"
    IFS=':'
  done
  IFS="$oldifs"
  printf '%s' "$out"
}
CLEANPATH="$(lhfree_path)"
mkdir -p "$TMP"

# A repo whose .git/hooks/pre-commit is a facsimile of lefthook's generated stub.
newrepo(){
  rm -rf "$1"; mkdir -p "$1"
  ( cd "$1" && git init -q && git config user.email t@t && git config user.name t && git config commit.gpgsign false && git commit -q --allow-empty -m init )
  local hooks; hooks="$(cd "$1" && cd "$(git rev-parse --git-common-dir)" && pwd)/hooks"
  mkdir -p "$hooks"
  cat > "$hooks/pre-commit" <<'STUB'
#!/bin/sh
if [ "$LEFTHOOK" = "0" ]; then
  exit 0
fi
call_lefthook()
{
  if test -n "$LEFTHOOK_BIN"
  then
    "$LEFTHOOK_BIN" "$@"
  elif lefthook -h >/dev/null 2>&1
  then
    lefthook "$@"
  else
    echo "Can't find lefthook in PATH"
  fi
}
call_lefthook run "pre-commit" "$@"
STUB
  chmod +x "$hooks/pre-commit"
}

# arm <repo>: splice the fail-closed block(s) the way init/ensure-present do.
arm(){ ( cd "$1" && bash "$IG" ); }

# A fake lefthook that logs every invocation and exits 0. $1 = path to place it.
write_fake_lefthook(){
  mkdir -p "$(dirname "$1")"
  cat > "$1" <<FAKE
#!/bin/sh
echo "\$@" >> "$TMP/lefthook-invocations.log"
exit 0
FAKE
  chmod +x "$1"
}

# try_commit <repo> <fixture-home> [extra env kv...]: one real commit attempt
# under env -i; echoes nothing, returns git's exit code, captures stderr.
try_commit(){
  local repo="$1" home="$2"; shift 2
  ( cd "$repo" \
    && echo "line $(date +%s%N 2>/dev/null || echo x)$RANDOM" >> f.txt \
    && git add f.txt \
    && env -i PATH="$CLEANPATH" HOME="$home" "$@" git commit -q -m tick ) >"$TMP/out" 2>"$TMP/err"
}

commits_in(){ ( cd "$1" && git rev-list --count HEAD ); }

echo "== H0: the two shipped install-guards.sh copies are byte-identical =="
if diff -q "$IG" "$IG_EMBEDDED" >/dev/null 2>&1; then
  pass "bin/install-guards.sh == internal/templates/files/install-guards.sh"
else
  fail "bin/ and embedded install-guards.sh copies have drifted apart"
fi

echo "== H1: cache-only lefthook heals via LEFTHOOK_BIN injection (gates RUN) =="
R1="$TMP/h1"; newrepo "$R1"; arm "$R1"
H1HOME="$TMP/h1-home"; rm -rf "$H1HOME" "$TMP/lefthook-invocations.log"
# A version dir that matches NO pin: the probe must be a version-agnostic glob.
write_fake_lefthook "$H1HOME/.cache/omakase/lefthook/9.9.9-notthepin/lefthook"
if try_commit "$R1" "$H1HOME"; then
  pass "commit succeeds with lefthook only in the omakase cache"
else
  fail "commit blocked despite a usable cached lefthook (rc=$?): $(cat "$TMP/err")"
fi
if grep -q "run pre-commit" "$TMP/lefthook-invocations.log" 2>/dev/null; then
  pass "the cached lefthook actually RAN the hook (heal, not just unblock)"
else
  fail "cached lefthook never invoked — fail-open skip still present"
fi

echo "== H2: no lefthook anywhere blocks the commit (fail closed) =="
R2="$TMP/h2"; newrepo "$R2"; arm "$R2"
H2HOME="$TMP/h2-home"; rm -rf "$H2HOME"; mkdir -p "$H2HOME"
BEFORE="$(commits_in "$R2")"
if try_commit "$R2" "$H2HOME"; then
  fail "commit SUCCEEDED with no lefthook anywhere — silent gate skip (fail-open)"
else
  pass "commit refused with no lefthook anywhere (rc!=0)"
fi
grep -q "omakase: BLOCKING" "$TMP/err" && pass "stderr carries the BLOCKING line" \
  || fail "no BLOCKING line on stderr: $(cat "$TMP/err")"
grep -q "LEFTHOOK_BIN" "$TMP/err" && pass "stderr names an escape hatch (LEFTHOOK_BIN)" \
  || fail "stderr gives no recovery guidance: $(cat "$TMP/err")"
[ "$(commits_in "$R2")" = "$BEFORE" ] && pass "no commit was created" \
  || fail "a commit landed despite the block"

echo "== H3: LEFTHOOK=0 skip is honored (no block on an empty machine) =="
R3="$TMP/h3"; newrepo "$R3"; arm "$R3"
if try_commit "$R3" "$H2HOME" LEFTHOOK=0; then
  pass "LEFTHOOK=0 commits cleanly with no lefthook anywhere (documented bypass)"
else
  fail "LEFTHOOK=0 was blocked (rc=$?): $(cat "$TMP/err")"
fi

echo "== H4: LEFTHOOK_BIN override resolves at tier 1 =="
R4="$TMP/h4"; newrepo "$R4"; arm "$R4"
rm -f "$TMP/lefthook-invocations.log"
FAKE4="$TMP/h4-fake/lefthook"; write_fake_lefthook "$FAKE4"
if try_commit "$R4" "$H2HOME" LEFTHOOK_BIN="$FAKE4"; then
  pass "commit succeeds with LEFTHOOK_BIN set"
else
  fail "LEFTHOOK_BIN run blocked (rc=$?): $(cat "$TMP/err")"
fi
grep -q "run pre-commit" "$TMP/lefthook-invocations.log" 2>/dev/null \
  && pass "LEFTHOOK_BIN lefthook ran the hook" \
  || fail "LEFTHOOK_BIN lefthook never invoked"

echo "== H5: splice is idempotent and replaces an old block =="
R5="$TMP/h5"; newrepo "$R5"
HOOKS5="$(cd "$R5" && cd "$(git rev-parse --git-common-dir)" && pwd)/hooks"
# Plant a STALE block between the same markers — a prior omakase version's text.
TABLE_STALE='# >>> omakase-harness fail-closed >>>
OLD_BLOCK_CONTENT_SENTINEL
# <<< omakase-harness fail-closed <<<'
{ head -n1 "$HOOKS5/pre-commit"; printf '%s\n' "$TABLE_STALE"; tail -n +2 "$HOOKS5/pre-commit"; } > "$HOOKS5/pre-commit.tmp"
mv "$HOOKS5/pre-commit.tmp" "$HOOKS5/pre-commit"; chmod +x "$HOOKS5/pre-commit"
arm "$R5"; arm "$R5"
N_BEGIN="$(grep -c '>>> omakase-harness fail-closed >>>' "$HOOKS5/pre-commit")"
[ "$N_BEGIN" = "1" ] && pass "exactly one fail-closed block after re-arming twice" \
  || fail "expected 1 fail-closed block, found $N_BEGIN"
grep -q "OLD_BLOCK_CONTENT_SENTINEL" "$HOOKS5/pre-commit" \
  && fail "stale block content survived the re-arm" \
  || pass "stale block content was replaced"
grep -q "verify-overlay.sh" "$HOOKS5/pre-commit" \
  && pass "current block content present after re-arm" \
  || fail "current block content missing after re-arm"

echo "== H6: a directory named lefthook in the cache blocks (never silent-skips) =="
R6="$TMP/h6"; newrepo "$R6"; arm "$R6"
H6HOME="$TMP/h6-home"; rm -rf "$H6HOME"
mkdir -p "$H6HOME/.cache/omakase/lefthook/2.1.9/lefthook"   # a DIR at the binary's path
BEFORE6="$(commits_in "$R6")"
if try_commit "$R6" "$H6HOME"; then
  fail "commit SUCCEEDED with a directory at the cached-lefthook path — silent fail-open"
else
  pass "commit refused when the cache entry is a directory (rc!=0)"
fi
grep -q "omakase: BLOCKING" "$TMP/err" && pass "directory case reaches the BLOCKING message" \
  || fail "directory case failed without the BLOCKING message: $(cat "$TMP/err")"
[ "$(commits_in "$R6")" = "$BEFORE6" ] && pass "no commit was created (H6)" \
  || fail "a commit landed despite the directory-case block"

rm -rf "$TMP"
echo ""
[ "$FAILED" -eq 0 ] && echo "ALL PASS" || { echo "FAILURES PRESENT"; exit 1; }
