#!/usr/bin/env bash
# Proof of the v1 safety guards (spec: docs/specs/2026-06-11-harness-manager-v1.md §4):
#   H. incumbent hook-manager guard — init refuses, before touching anything
#   I. guarded cut-over — --cut-over refuses without OMAKASE_CUTOVER_CONFIRM=1
#   J. upstream-collision guard — a placed path turning TRACKED warns loudly
#   K. fail-closed gates — a wiped overlay BLOCKS commits instead of passing silently
set -u
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INIT="$HERE/../bin/init.sh"
REMOVE="$HERE/../bin/remove.sh"
LEFTHOOK="${LEFTHOOK_BIN:-/Users/ericshen/Claude/pixterm-engine/node_modules/.bin/lefthook}"
TMP="${TMPDIR:-/tmp}/omakase-safety-test.$$"
FAILED=0
pass(){ echo "  PASS: $1"; }
fail(){ echo "  FAIL: $1"; FAILED=1; }

mkpayload(){ # $1 = payload dir
  local p="$1"
  mkdir -p "$p/.omakase/gates"
  cat > "$p/.omakase/gates/example.sh" <<'SH'
#!/usr/bin/env bash
echo "omakase-example-gate-ran"
exit 0
SH
  cat > "$p/lefthook-local.yml" <<'YML'
pre-commit:
  jobs:
    - name: omakase-example
      run: bash .omakase/gates/example.sh
post-checkout:
  jobs:
    - name: omakase-ensure-present
      run: bash "$(git rev-parse --git-common-dir)/omakase/ensure-present.sh"
YML
}

newrepo(){ rm -rf "$1"; mkdir -p "$1"; ( cd "$1" && git init -q && git config user.email t@t && git config user.name t && git config commit.gpgsign false && git commit -q --allow-empty -m init ); }

export PATH="$(dirname "$LEFTHOOK"):$PATH"

# ---------- Scenario H: incumbent hook-manager guard ----------
echo "== Scenario H: init refuses when an incumbent hook manager is present =="
PAY="$TMP/payH"; mkpayload "$PAY"

# H1: husky directory — refuse before any mutation
REPO="$TMP/repoH1"; newrepo "$REPO"; mkdir -p "$REPO/.husky"
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
[ "$rc" -ne 0 ] && pass "refused on .husky/ (exit $rc)" || fail "did not refuse on .husky/"
echo "$OUT" | grep -qi 'husky' && pass "refusal names husky" || fail "refusal does not name husky ($OUT)"
[ ! -e "$REPO/.omakase" ] && pass "placed nothing before refusing" || fail "placed files despite refusal"
grep -q "omakase-harness" "$REPO/.git/info/exclude" 2>/dev/null && fail "wrote exclude block despite refusal" || pass "exclude block untouched"
[ ! -f "$REPO/.git/hooks/pre-commit" ] && pass "no hook stub installed" || fail "hook stub installed despite refusal"

# H2: package.json "prepare": "husky" (reinstalls husky over lefthook on npm install)
REPO="$TMP/repoH2"; newrepo "$REPO"
printf '{ "scripts": { "prepare": "husky" } }\n' > "$REPO/package.json"
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
{ [ "$rc" -ne 0 ] && echo "$OUT" | grep -qi 'husky'; } && pass "refused on package.json prepare:husky" || fail "did not refuse on prepare:husky ($OUT)"

# H3: foreign core.hooksPath (husky v9 sets .husky/_)
REPO="$TMP/repoH3"; newrepo "$REPO"
( cd "$REPO" && git config core.hooksPath .husky/_ )
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
{ [ "$rc" -ne 0 ] && echo "$OUT" | grep -q 'core.hooksPath'; } && pass "refused on foreign core.hooksPath, named it" || fail "did not refuse on core.hooksPath ($OUT)"

# H4: pre-commit framework — config file + installed stub in .git/hooks
REPO="$TMP/repoH4"; newrepo "$REPO"
printf 'repos: []\n' > "$REPO/.pre-commit-config.yaml"
printf '#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\nexit 0\n' > "$REPO/.git/hooks/pre-commit"
chmod +x "$REPO/.git/hooks/pre-commit"
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
{ [ "$rc" -ne 0 ] && echo "$OUT" | grep -qi 'pre-commit'; } && pass "refused on installed pre-commit framework" || fail "did not refuse on pre-commit framework ($OUT)"

# H5: a plain hand-written hook file — refuse, and leave it exactly in place
REPO="$TMP/repoH5"; newrepo "$REPO"
printf '#!/bin/sh\necho team-gate\nexit 1\n' > "$REPO/.git/hooks/pre-push"; chmod +x "$REPO/.git/hooks/pre-push"
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
[ "$rc" -ne 0 ] && pass "refused on an existing non-lefthook hook file" || fail "did not refuse on a foreign hook file"
grep -q 'team-gate' "$REPO/.git/hooks/pre-push" 2>/dev/null && pass "incumbent hook left untouched (not displaced to .old)" || fail "incumbent hook was displaced"

# H6: no false positives — samples-only repo installs; re-init tolerates lefthook's own stubs
REPO="$TMP/repoH6"; newrepo "$REPO"
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
[ "$rc" -eq 0 ] && pass "clean repo (.sample hooks only) installs fine" || fail "refused a clean repo ($OUT)"
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
[ "$rc" -eq 0 ] && pass "re-init does not trip over lefthook's own stubs" || fail "re-init refused its own stubs ($OUT)"
( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$REMOVE" ) >/dev/null 2>&1

rm -rf "$TMP"
echo ""
[ "$FAILED" -eq 0 ] && echo "ALL PASS" || { echo "FAILURES PRESENT"; exit 1; }
