#!/usr/bin/env bash
# Proof of the v1 safety guards (spec: docs/specs/2026-06-11-harness-manager-v1.md §4):
#   H. incumbent hook-manager guard — init refuses, before touching anything
#   I. guarded cut-over — --cut-over refuses without OMAKASE_CUTOVER_CONFIRM=1
#   J. upstream-collision guard — a placed path turning TRACKED warns loudly
#   K. fail-closed gates — a wiped overlay BLOCKS commits instead of passing silently
set -u
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INIT="$HERE/../bin/init.sh"
REMOVE="$HERE/../bin/remove.sh"
LEFTHOOK="${LEFTHOOK_BIN:-/Users/ericshen/Claude/pixterm-engine/node_modules/.bin/lefthook}"
TMP="${TMPDIR:-/tmp}/omakase-safety-test.$$"
FAILED=0
pass(){ echo "  PASS: $1"; }
fail(){ echo "  FAIL: $1"; FAILED=1; }

mkpayload(){ # $1 = payload dir
  local p="$1"
  mkdir -p "$p/.omakase/gates"
  cat > "$p/.omakase/gates/example.sh" <<'SH'
#!/usr/bin/env bash
echo "omakase-example-gate-ran"
exit 0
SH
  cat > "$p/lefthook-local.yml" <<'YML'
pre-commit:
  jobs:
    - name: omakase-example
      run: bash .omakase/gates/example.sh
post-checkout:
  jobs:
    - name: omakase-ensure-present
      run: bash "$(git rev-parse --git-common-dir)/omakase/ensure-present.sh"
YML
}

newrepo(){ rm -rf "$1"; mkdir -p "$1"; ( cd "$1" && git init -q && git config user.email t@t && git config user.name t && git config commit.gpgsign false && git commit -q --allow-empty -m init ); }

export PATH="$(dirname "$LEFTHOOK"):$PATH"

# ---------- Scenario H: incumbent hook-manager guard ----------
echo "== Scenario H: init refuses when an incumbent hook manager is present =="
PAY="$TMP/payH"; mkpayload "$PAY"

# H1: husky directory — refuse before any mutation
REPO="$TMP/repoH1"; newrepo "$REPO"; mkdir -p "$REPO/.husky"
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
[ "$rc" -ne 0 ] && pass "refused on .husky/ (exit $rc)" || fail "did not refuse on .husky/"
echo "$OUT" | grep -qi 'husky' && pass "refusal names husky" || fail "refusal does not name husky ($OUT)"
[ ! -e "$REPO/.omakase" ] && pass "placed nothing before refusing" || fail "placed files despite refusal"
grep -q "omakase-harness" "$REPO/.git/info/exclude" 2>/dev/null && fail "wrote exclude block despite refusal" || pass "exclude block untouched"
[ ! -f "$REPO/.git/hooks/pre-commit" ] && pass "no hook stub installed" || fail "hook stub installed despite refusal"

# H2: package.json "prepare": "husky" (reinstalls husky over lefthook on npm install)
REPO="$TMP/repoH2"; newrepo "$REPO"
printf '{ "scripts": { "prepare": "husky" } }\n' > "$REPO/package.json"
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
{ [ "$rc" -ne 0 ] && echo "$OUT" | grep -qi 'husky'; } && pass "refused on package.json prepare:husky" || fail "did not refuse on prepare:husky ($OUT)"

# H3: foreign core.hooksPath (husky v9 sets .husky/_)
REPO="$TMP/repoH3"; newrepo "$REPO"
( cd "$REPO" && git config core.hooksPath .husky/_ )
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
{ [ "$rc" -ne 0 ] && echo "$OUT" | grep -q 'core.hooksPath'; } && pass "refused on foreign core.hooksPath, named it" || fail "did not refuse on core.hooksPath ($OUT)"

# H4: pre-commit framework — config file + installed stub in .git/hooks
REPO="$TMP/repoH4"; newrepo "$REPO"
printf 'repos: []\n' > "$REPO/.pre-commit-config.yaml"
printf '#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\nexit 0\n' > "$REPO/.git/hooks/pre-commit"
chmod +x "$REPO/.git/hooks/pre-commit"
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
{ [ "$rc" -ne 0 ] && echo "$OUT" | grep -qi 'pre-commit'; } && pass "refused on installed pre-commit framework" || fail "did not refuse on pre-commit framework ($OUT)"

# H5: a plain hand-written hook file — refuse, and leave it exactly in place
REPO="$TMP/repoH5"; newrepo "$REPO"
printf '#!/bin/sh\necho team-gate\nexit 1\n' > "$REPO/.git/hooks/pre-push"; chmod +x "$REPO/.git/hooks/pre-push"
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
[ "$rc" -ne 0 ] && pass "refused on an existing non-lefthook hook file" || fail "did not refuse on a foreign hook file"
grep -q 'team-gate' "$REPO/.git/hooks/pre-push" 2>/dev/null && pass "incumbent hook left untouched (not displaced to .old)" || fail "incumbent hook was displaced"

# H6: no false positives — samples-only repo installs; re-init tolerates lefthook's own stubs
REPO="$TMP/repoH6"; newrepo "$REPO"
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
[ "$rc" -eq 0 ] && pass "clean repo (.sample hooks only) installs fine" || fail "refused a clean repo ($OUT)"
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
[ "$rc" -eq 0 ] && pass "re-init does not trip over lefthook's own stubs" || fail "re-init refused its own stubs ($OUT)"
( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$REMOVE" ) >/dev/null 2>&1

# ---------- Scenario I: guarded cut-over ----------
echo "== Scenario I: guarded cut-over =="
PAY="$TMP/payI"; mkpayload "$PAY"; printf 'payload agents\n' > "$PAY/AGENTS.md"
REPO="$TMP/repoI"; newrepo "$REPO"
( cd "$REPO" && printf 'COMMITTED agents\n' > AGENTS.md && git add AGENTS.md && git commit -q -m team )

# I1: plain init skips the committed file and advises the GUARDED form, not the raw command
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 )
echo "$OUT" | grep -q 'cut-over' && pass "skip advice points at the guarded cut-over" || fail "skip advice does not mention cut-over ($OUT)"
echo "$OUT" | grep -q 'git rm --cached' && fail "raw 'git rm --cached' still advised by plain init" || pass "raw git rm --cached no longer advised by plain init"

# I2: --cut-over without confirmation refuses and mutates nothing
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" --cut-over 2>&1 ); rc=$?
[ "$rc" -ne 0 ] && pass "cut-over refused without OMAKASE_CUTOVER_CONFIRM (exit $rc)" || fail "cut-over proceeded without confirmation"
echo "$OUT" | grep -q 'AGENTS.md' && pass "refusal names the file it would untrack" || fail "refusal does not name the file ($OUT)"
echo "$OUT" | grep -qi 'EVERYONE' && pass "refusal states the shared consequence" || fail "no shared-consequence statement ($OUT)"
( cd "$REPO" && git ls-files --error-unmatch AGENTS.md >/dev/null 2>&1 ) && pass "AGENTS.md still tracked after refusal" || fail "refusal still untracked the file"
[ -z "$(cd "$REPO" && git status --porcelain)" ] && pass "nothing staged after refusal" || fail "refusal left staged changes"
grep -q 'COMMITTED agents' "$REPO/AGENTS.md" && pass "committed content untouched after refusal" || fail "refusal touched the committed file"

# I3: with confirmation — untracks, stages the deletion, injected copy takes over on disk
OUT=$( cd "$REPO" && OMAKASE_CUTOVER_CONFIRM=1 OMAKASE_PAYLOAD="$PAY" bash "$INIT" --cut-over 2>&1 ); rc=$?
[ "$rc" -eq 0 ] && pass "confirmed cut-over proceeds (exit 0)" || fail "confirmed cut-over failed ($OUT)"
( cd "$REPO" && git ls-files --error-unmatch AGENTS.md >/dev/null 2>&1 ) && fail "AGENTS.md still tracked after confirmed cut-over" || pass "AGENTS.md untracked"
( cd "$REPO" && git status --porcelain ) | grep -q '^D  AGENTS.md' && pass "deletion STAGED for the user to review + commit" || fail "no staged deletion in git status"
[ -f "$REPO/AGENTS.md" ] && pass "file stays on disk" || fail "file deleted from disk"
grep -q 'payload agents' "$REPO/AGENTS.md" && pass "injected copy took over the path" || fail "injected copy did not take over"

# I4: --cut-over with nothing tracked is a no-op that still inits
REPO2="$TMP/repoI2"; newrepo "$REPO2"
OUT=$( cd "$REPO2" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" --cut-over 2>&1 ); rc=$?
{ [ "$rc" -eq 0 ] && echo "$OUT" | grep -qi 'nothing to cut over'; } && pass "cut-over with nothing tracked: no-op, init proceeds" || fail "empty cut-over mishandled ($OUT)"

# I5: --help documents the escape hatch
OUT=$( bash "$INIT" --help 2>&1 ); rc=$?
{ [ "$rc" -eq 0 ] && echo "$OUT" | grep -q 'cut-over' && echo "$OUT" | grep -q 'OMAKASE_CUTOVER_CONFIRM'; } && pass "--help documents --cut-over + the confirmation env" || fail "--help missing cut-over docs ($OUT)"

# ---------- Scenario J: upstream-collision guard ----------
echo "== Scenario J: a placed path turning TRACKED warns loudly =="
PAY="$TMP/payJ"; mkpayload "$PAY"
REPO="$TMP/repoJ"; newrepo "$REPO"
( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" ) >/dev/null 2>&1
COMMON="$(cd "$REPO" && cd "$(git rev-parse --git-common-dir)" && pwd)"
# Simulate an upstream commit landing a tracked file at a placed path (same end state
# as a pull: the index tracks the path, the working copy is upstream's content).
( cd "$REPO" && printf 'UPSTREAM CONTENT\n' > .omakase/gates/example.sh && git add -f .omakase/gates/example.sh && LEFTHOOK=0 git commit -q -m upstream )

# J1: the post-checkout self-heal warns (the timely surface) and never touches the tracked file
ERR=$( cd "$REPO" && bash "$COMMON/omakase/ensure-present.sh" 2>&1 )
echo "$ERR" | grep -qi 'WARNING' && pass "ensure-present warns on the tracked collision" || fail "ensure-present silent on collision ($ERR)"
echo "$ERR" | grep -q '.omakase/gates/example.sh' && pass "ensure-present warning names the file" || fail "warning does not name the file ($ERR)"
echo "$ERR" | grep -qi 'clobber' && pass "warning says the personal copy was likely clobbered" || fail "warning missing the clobber explanation ($ERR)"
grep -q 'UPSTREAM CONTENT' "$REPO/.omakase/gates/example.sh" && pass "tracked file left untouched" || fail "self-heal touched a tracked file"

# J2: re-init warns too and preserves the last-injected copy before rebuilding the snapshot
OUT=$( cd "$REPO" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 ); rc=$?
[ "$rc" -eq 0 ] && pass "re-init still completes (warn, not block)" || fail "re-init failed on collision ($OUT)"
echo "$OUT" | grep -qi 'WARNING' && pass "init warns on the placed->tracked path" || fail "init silent on collision ($OUT)"
echo "$OUT" | grep -q '.omakase/gates/example.sh' && pass "init warning names the file" || fail "init warning does not name the file ($OUT)"
echo "$OUT" | grep -qi 'clobber' && pass "init warning explains the likely clobber" || fail "init warning missing clobber explanation ($OUT)"
echo "$OUT" | grep -q 'clobbered/' && pass "init warning points at the preserved copy" || fail "init warning missing the preserved-copy path ($OUT)"
grep -q 'omakase-example-gate-ran' "$COMMON/omakase/clobbered/.omakase/gates/example.sh" 2>/dev/null && pass "last-injected copy preserved under clobbered/" || fail "preserved copy missing or wrong"

# J3: no false warning on a clean re-init
REPO2="$TMP/repoJ2"; newrepo "$REPO2"
( cd "$REPO2" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" ) >/dev/null 2>&1
OUT=$( cd "$REPO2" && OMAKASE_PAYLOAD="$PAY" bash "$INIT" 2>&1 )
echo "$OUT" | grep -qi 'NOW TRACKED' && fail "false collision warning on a clean re-init ($OUT)" || pass "no false warning on a clean re-init"

rm -rf "$TMP"
echo ""
[ "$FAILED" -eq 0 ] && echo "ALL PASS" || { echo "FAILURES PRESENT"; exit 1; }
